import fs from 'node:fs/promises'
import Ajv from 'ajv'
import standalone from 'ajv/dist/standalone/index.js'
import { contracts } from '../src/index.mjs'
import { executionTypes, executionLimits } from '../src/execution.mjs'
import { mcpTypes, mcpLimits } from '../src/mcp.mjs'

const named = { ...executionTypes, ...mcpTypes }
function type(schema, defining) {
  const name = Object.keys(named).find(name => named[name] === schema && name !== defining)
  if (name) return name
  if (schema === true || !Object.keys(schema).length) return 'unknown'
  if (schema === false) return 'never'
  if (schema.const !== undefined) return JSON.stringify(schema.const)
  if (schema.enum) return schema.enum.map(value => JSON.stringify(value)).join(' | ')
  if (schema.anyOf) return schema.anyOf.map(value => type(value)).join(' | ')
  if (Array.isArray(schema.type)) return schema.type.map(value => type({ ...schema, type: value })).join(' | ')
  if (schema.type === 'object') {
    const props = Object.entries(schema.properties || {}).map(([key, value]) => `${JSON.stringify(key)}${schema.required?.includes(key) ? '' : '?'}: ${type(value)}`)
    if (schema.additionalProperties) props.push(`[key: string]: ${schema.additionalProperties === true ? 'unknown' : type(schema.additionalProperties)}`)
    return props.length ? `{ ${props.join('; ')} }` : 'Record<string, never>'
  }
  if (schema.type === 'array') return `Array<${type(schema.items)}>`
  if (schema.type === 'integer' || schema.type === 'number') return 'number'
  if (['string', 'boolean', 'null'].includes(schema.type)) return schema.type
  throw new Error(`Unsupported schema: ${JSON.stringify(schema)}`)
}
let declarations = '// Generated by scripts/generate.mjs. Edit the source contracts.\n'
for (const [name, schema] of Object.entries(named)) declarations += `export type ${name} = ${type(schema, name)}\n`
declarations += `export const executionLimits: ${JSON.stringify(executionLimits).replace(/,/g, ';')}\nexport const mcpLimits: ${JSON.stringify(mcpLimits).replace(/,/g, ';')}\n`
declarations += 'export const contracts: Record<string, { types: string; methods: Record<string, { permission: string; input: object; output: object; surfaces: string[]; errors: string[]; limits?: Record<string, number> }>; events: Record<string, { permission: string; input: object }> }>\n'
const ajv = new Ajv({ strict: false, allErrors: true, code: { source: true, esm: true, lines: true } })
const exports = {}, keys = {}, schemas = new Map()
function register(schema, key) {
  let id = schemas.get(schema)
  if (!id) {
    id = `v${schemas.size}`
    schemas.set(schema, id)
    ajv.addSchema(schema, id)
    exports[id] = id
  }
  keys[key] = id
}
let docs = '# Generated Host contracts\n\nSource: `src/execution.mjs`, `src/mcp.mjs`. Run `node scripts/generate.mjs --check` in CI.\n\n| Protocol / method | Permission | Input fields (* required) | Caller | Semantics / limits |\n| --- | --- | --- | --- | --- |\n'
for (const [protocol, definition] of Object.entries(contracts)) {
  for (const direction of ['Input', 'Output']) {
    declarations += `export interface ${definition.types}Host${direction}Map {\n`
    for (const [name, method] of Object.entries(definition.methods)) declarations += `  ${JSON.stringify(name)}: ${type(method[direction.toLowerCase()])}\n`
    declarations += '}\n'
  }
  for (const [name, method] of Object.entries(definition.methods)) {
    for (const direction of ['input', 'output']) {
      register(method[direction], JSON.stringify([protocol, name, direction]))
    }
    const fields = Object.keys(method.input.properties).map(key => `${key}${method.input.required?.includes(key) ? '*' : ''}`).join(', ')
    docs += `| ${protocol} / ${name} | ${method.permission} | ${fields || '{}'} | ${method.surfaces.join(', ')} | ${[method.idempotency && 'idempotency: ' + method.idempotency, method.offsetUnit, method.limits && JSON.stringify(method.limits)].filter(Boolean).join('; ')} |\n`
  }
  for (const [name, event] of Object.entries(definition.events)) {
    register(event.input, JSON.stringify([protocol, name, 'event']))
  }
}
const imports = new Map()
const generated = standalone(ajv, exports).replace(/require\("([^"\n]+)"\)(\.default)?/g, (_match, module, property) => {
  if (!imports.has(module)) imports.set(module, 'runtime' + imports.size)
  const name = imports.get(module)
  return property ? `(${name}.default || ${name})` : name
})
const prelude = [...imports].map(([module, name]) => `import ${name} from '${module}.js'`).join('\n')
const outputs = {
  'src/generated.d.mts': declarations,
  'src/generated-validators.mjs': prelude + '\n' + generated + '\nexport const validatorKeys = ' + JSON.stringify(keys, null, 2) + '\n',
  'README.md': docs,
}
for (const [path, content] of Object.entries(outputs)) {
  const url = new URL('../' + path, import.meta.url)
  if (process.argv.includes('--check')) {
    if (await fs.readFile(url, 'utf8') !== content) throw new Error(`Stale generated contract: ${path}`)
  } else await fs.writeFile(url, content)
}
