import fs from 'node:fs/promises'
import ts from 'typescript'

const root = new URL('../', import.meta.url)
const manifest = JSON.parse(await fs.readFile(new URL('package.json', root), 'utf8'))
const declaration = await fs.readFile(new URL('src/index.d.mts', root), 'utf8')
const ast = ts.createSourceFile('index.d.mts', declaration, ts.ScriptTarget.Latest, true)
const types = ast.statements.filter(n => ts.isInterfaceDeclaration(n) || ts.isTypeAliasDeclaration(n)).map(n => n.name.text)
for (const [name, entry] of Object.entries(manifest.exports)) {
  if (['.', './execution', './ui', './testing', './mcp', './results', './results/store'].includes(name)) continue
  const values = Object.keys(await import(new URL(entry.import, root)))
  const content = `// Generated by scripts/export-types.mjs.\nexport { ${values.sort().join(', ')} } from '../index.mjs'\nexport type { ${types.sort().join(', ')} } from '../index.mjs'\n`
  const target = entry.import.replace(/\.mjs$/, '.d.mts')
  if (process.argv.includes('--check')) {
    if (entry.types !== target || await fs.readFile(new URL(target, root), 'utf8') !== content) throw new Error(`Stale types: ${name}`)
  } else {
    await fs.writeFile(new URL(target, root), content)
    entry.types = target
  }
}
if (!process.argv.includes('--check')) await fs.writeFile(new URL('package.json', root), JSON.stringify(manifest, null, 2) + '\n')
