// Initial MySQL 8.4 schema for fresh databases. No legacy conversion.
export const mysqlSchema: string[] = [
  `CREATE TABLE IF NOT EXISTS organizations (
    id VARCHAR(128) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at BIGINT NOT NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE TABLE IF NOT EXISTS departments (
    id VARCHAR(128) PRIMARY KEY,
    org_id VARCHAR(128) NOT NULL,
    parent_id VARCHAR(128),
    name VARCHAR(255) NOT NULL,
    token_limit BIGINT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    FOREIGN KEY (\`org_id\`) REFERENCES organizations(\`id\`),
    FOREIGN KEY (\`parent_id\`) REFERENCES departments(\`id\`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(128) PRIMARY KEY,
    org_id VARCHAR(128) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    department_id VARCHAR(128),
    role VARCHAR(191) NOT NULL DEFAULT 'user',
    status VARCHAR(191) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    password_hash VARCHAR(191),
    password_updated_at BIGINT,
    last_login_at BIGINT,
    token_limit BIGINT,
    created_at BIGINT NOT NULL,
    FOREIGN KEY (\`org_id\`) REFERENCES organizations(\`id\`),
    FOREIGN KEY (\`department_id\`) REFERENCES departments(\`id\`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE TABLE IF NOT EXISTS roles (
    id VARCHAR(128) PRIMARY KEY,
    org_id VARCHAR(128) NOT NULL,
    system_key VARCHAR(191),
    name VARCHAR(255) NOT NULL,
    description LONGTEXT NOT NULL DEFAULT (''),
    is_builtin BIGINT NOT NULL DEFAULT 0 CHECK (is_builtin IN (0, 1)),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    UNIQUE (org_id, name),
    UNIQUE (org_id, system_key),
    FOREIGN KEY (\`org_id\`) REFERENCES organizations(\`id\`) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE TABLE IF NOT EXISTS role_permissions (
    role_id VARCHAR(128) NOT NULL,
    permission VARCHAR(191) NOT NULL,
    PRIMARY KEY (role_id, permission),
    FOREIGN KEY (\`role_id\`) REFERENCES roles(\`id\`) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE TABLE IF NOT EXISTS user_roles (
    user_id VARCHAR(128) NOT NULL,
    role_id VARCHAR(128) NOT NULL,
    created_at BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (\`user_id\`) REFERENCES users(\`id\`) ON DELETE CASCADE,
    FOREIGN KEY (\`role_id\`) REFERENCES roles(\`id\`) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE TABLE IF NOT EXISTS api_keys (
    id VARCHAR(128) PRIMARY KEY,
    org_id VARCHAR(128) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    name VARCHAR(255) NOT NULL,
    prefix VARCHAR(64) NOT NULL,
    secret_hash VARCHAR(191) NOT NULL,
    scopes_json LONGTEXT NOT NULL,
    status VARCHAR(191) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked')),
    created_at BIGINT NOT NULL,
    last_used_at BIGINT,
    FOREIGN KEY (\`org_id\`) REFERENCES organizations(\`id\`),
    FOREIGN KEY (\`user_id\`) REFERENCES users(\`id\`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE TABLE IF NOT EXISTS oauth_identities (
    provider_id VARCHAR(128) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    email VARCHAR(255) NOT NULL,
    api_key_id VARCHAR(128),
    created_at BIGINT NOT NULL,
    last_login_at BIGINT NOT NULL,
    PRIMARY KEY (provider_id, subject),
    UNIQUE (provider_id, user_id),
    FOREIGN KEY (\`user_id\`) REFERENCES users(\`id\`),
    FOREIGN KEY (\`api_key_id\`) REFERENCES api_keys(\`id\`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE TABLE IF NOT EXISTS oauth_authorization_requests (
    id VARCHAR(128) PRIMARY KEY,
    redirect_uri LONGTEXT NOT NULL,
    state VARCHAR(191) NOT NULL,
    code_challenge VARCHAR(191) NOT NULL,
    expires_at BIGINT NOT NULL,
    password_attempts BIGINT NOT NULL DEFAULT 0
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE TABLE IF NOT EXISTS oauth_authorization_codes (
    code VARCHAR(191) PRIMARY KEY,
    redirect_uri LONGTEXT NOT NULL,
    state VARCHAR(191) NOT NULL,
    code_challenge VARCHAR(191) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    org_id VARCHAR(128) NOT NULL,
    expires_at BIGINT NOT NULL,
    FOREIGN KEY (\`user_id\`) REFERENCES users(\`id\`),
    FOREIGN KEY (\`org_id\`) REFERENCES organizations(\`id\`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE TABLE IF NOT EXISTS server_config (
    \`key\` VARCHAR(191) PRIMARY KEY,
    value LONGTEXT NOT NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE INDEX departments_org_idx ON departments (org_id)`,
  `CREATE INDEX departments_parent_idx ON departments (parent_id)`,
  `CREATE INDEX users_org_idx ON users (org_id)`,
  `CREATE INDEX users_email_idx ON users (email)`,
  `CREATE INDEX roles_org_idx ON roles (org_id)`,
  `CREATE INDEX user_roles_role_idx ON user_roles (role_id)`,
  `CREATE INDEX api_keys_org_idx ON api_keys (org_id)`,
  `CREATE INDEX api_keys_user_idx ON api_keys (user_id)`,
  `CREATE INDEX oauth_identities_user_idx ON oauth_identities (user_id)`,
  `CREATE INDEX oauth_authorization_requests_expiry_idx
  ON oauth_authorization_requests (expires_at)`,
  `CREATE INDEX oauth_authorization_codes_expiry_idx
  ON oauth_authorization_codes (expires_at)`,
  `CREATE TABLE IF NOT EXISTS sessions (
    session_id VARCHAR(128) PRIMARY KEY,
    transcript_session_id VARCHAR(128) NOT NULL,
    org_id VARCHAR(128) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    role VARCHAR(191) NOT NULL,
    scopes_json LONGTEXT NOT NULL,
    cwd LONGTEXT NOT NULL,
    docker_image VARCHAR(191),
    profile_dir LONGTEXT NOT NULL,
    workspace_dir LONGTEXT,
    transcript_dir LONGTEXT NOT NULL,
    container_name VARCHAR(191),
    status VARCHAR(191) NOT NULL,
    desired_state VARCHAR(191) NOT NULL,
    current_attempt_id VARCHAR(128),
    transcript_path LONGTEXT NOT NULL,
    title LONGTEXT,
    summary LONGTEXT,
    assistant_name LONGTEXT,
    advanced_settings_json LONGTEXT NOT NULL DEFAULT ('{}'),
    auto_memory_json LONGTEXT NOT NULL DEFAULT ('{}'),
    session_memory_json LONGTEXT NOT NULL DEFAULT ('{}'),
    runtime_options_json LONGTEXT NOT NULL DEFAULT ('{}'),
    created_at BIGINT NOT NULL,
    last_active_at BIGINT NOT NULL,
    ended_at BIGINT,
    deleted_at BIGINT
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE TABLE IF NOT EXISTS session_attempts (
    attempt_id VARCHAR(128) PRIMARY KEY,
    session_id VARCHAR(128) NOT NULL,
    generation BIGINT NOT NULL,
    runtime_state VARCHAR(191) NOT NULL,
    server_instance_id VARCHAR(128),
    runner_pid BIGINT,
    container_name VARCHAR(191),
    attempt_dir LONGTEXT NOT NULL,
    manifest_path LONGTEXT NOT NULL,
    attach_path LONGTEXT,
    resume_transcript_session_id VARCHAR(128) NOT NULL,
    started_at BIGINT NOT NULL,
    last_heartbeat_at BIGINT,
    stopped_at BIGINT,
    exit_code BIGINT,
    exit_signal VARCHAR(191),
    stop_reason VARCHAR(191),
    error_text LONGTEXT,
    UNIQUE (session_id, generation),
    FOREIGN KEY (\`session_id\`) REFERENCES sessions(\`session_id\`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE TABLE IF NOT EXISTS server_instances (
    instance_id VARCHAR(128) PRIMARY KEY,
    host VARCHAR(191) NOT NULL,
    pid BIGINT,
    started_at BIGINT NOT NULL,
    heartbeat_at BIGINT NOT NULL,
    stopped_at BIGINT,
    status VARCHAR(191) NOT NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE TABLE IF NOT EXISTS session_events (
    event_id VARCHAR(128) PRIMARY KEY,
    session_id VARCHAR(128) NOT NULL,
    attempt_id VARCHAR(128),
    event_type VARCHAR(191) NOT NULL,
    payload_json LONGTEXT NOT NULL,
    created_at BIGINT NOT NULL,
    FOREIGN KEY (\`session_id\`) REFERENCES sessions(\`session_id\`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE INDEX sessions_user_idx
  ON sessions (org_id, user_id, last_active_at DESC)`,
  `CREATE INDEX sessions_state_idx
  ON sessions (org_id, status, last_active_at DESC)`,
  `CREATE INDEX attempts_session_idx
  ON session_attempts (session_id, generation DESC)`,
  `CREATE TABLE IF NOT EXISTS agent_mail_messages (
    id VARCHAR(128) PRIMARY KEY,
    org_id VARCHAR(128) NOT NULL,
    from_user_id VARCHAR(128) NOT NULL,
    to_user_id VARCHAR(128) NOT NULL,
    client_message_id VARCHAR(128) NOT NULL,
    subject LONGTEXT NOT NULL DEFAULT (''),
    content LONGTEXT NOT NULL,
    thread_id VARCHAR(128) NOT NULL,
    reply_to VARCHAR(191),
    hop_count BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(191) NOT NULL CHECK (status IN ('queued','leased','accepted','running','completed','failed','expired')),
    consumer_id VARCHAR(128),
    lease_token_hash VARCHAR(191),
    lease_until BIGINT,
    attempts BIGINT NOT NULL DEFAULT 0,
    error LONGTEXT,
    created_at BIGINT NOT NULL,
    expires_at BIGINT NOT NULL,
    accepted_at BIGINT,
    completed_at BIGINT,
    UNIQUE(from_user_id, client_message_id),
    FOREIGN KEY (\`org_id\`) REFERENCES organizations(\`id\`),
    FOREIGN KEY (\`from_user_id\`) REFERENCES users(\`id\`),
    FOREIGN KEY (\`to_user_id\`) REFERENCES users(\`id\`),
    FOREIGN KEY (\`reply_to\`) REFERENCES agent_mail_messages(\`id\`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE INDEX agent_mail_messages_recipient_idx
  ON agent_mail_messages (org_id, to_user_id, status, created_at)`,
  `CREATE INDEX agent_mail_messages_sender_idx
  ON agent_mail_messages (org_id, from_user_id, created_at DESC)`,
  `CREATE INDEX agent_mail_messages_thread_idx
  ON agent_mail_messages (org_id, thread_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS agent_mail_deletions (
    message_id VARCHAR(128) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    deleted_at BIGINT NOT NULL,
    PRIMARY KEY (message_id, user_id),
    FOREIGN KEY (\`message_id\`) REFERENCES agent_mail_messages(\`id\`) ON DELETE CASCADE,
    FOREIGN KEY (\`user_id\`) REFERENCES users(\`id\`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE INDEX agent_mail_deletions_user_idx
  ON agent_mail_deletions (user_id, deleted_at)`,
  `CREATE TABLE IF NOT EXISTS agent_mail_consumers (
    org_id VARCHAR(128) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    consumer_id VARCHAR(128) NOT NULL,
    lease_until BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (org_id, user_id),
    FOREIGN KEY (\`org_id\`) REFERENCES organizations(\`id\`),
    FOREIGN KEY (\`user_id\`) REFERENCES users(\`id\`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE TABLE IF NOT EXISTS agent_mail_acl (
    org_id VARCHAR(128) NOT NULL,
    owner_user_id VARCHAR(128) NOT NULL,
    sender_user_id VARCHAR(128) NOT NULL,
    mode VARCHAR(191) NOT NULL CHECK (mode IN ('blocked','manual','auto')),
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (org_id, owner_user_id, sender_user_id),
    FOREIGN KEY (\`org_id\`) REFERENCES organizations(\`id\`),
    FOREIGN KEY (\`owner_user_id\`) REFERENCES users(\`id\`),
    FOREIGN KEY (\`sender_user_id\`) REFERENCES users(\`id\`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE TABLE IF NOT EXISTS openim_bindings (
    id VARCHAR(128) PRIMARY KEY,
    org_id VARCHAR(128) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    instance_id VARCHAR(128) NOT NULL,
    openim_user_id VARCHAR(128) NOT NULL,
    profile_hash VARCHAR(191) NOT NULL DEFAULT '',
    provisioned_at BIGINT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    UNIQUE (instance_id, user_id),
    UNIQUE (instance_id, openim_user_id),
    FOREIGN KEY (\`org_id\`) REFERENCES organizations(\`id\`) ON DELETE CASCADE,
    FOREIGN KEY (\`user_id\`) REFERENCES users(\`id\`) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE INDEX openim_bindings_org_idx
  ON openim_bindings (org_id, instance_id)`,
  `CREATE TABLE IF NOT EXISTS openim_group_bindings (
    id VARCHAR(128) PRIMARY KEY,
    org_id VARCHAR(128) NOT NULL,
    instance_id VARCHAR(128) NOT NULL,
    openim_group_id VARCHAR(128) NOT NULL,
    created_by_user_id VARCHAR(128) NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    UNIQUE (instance_id, openim_group_id),
    FOREIGN KEY (\`org_id\`) REFERENCES organizations(\`id\`) ON DELETE CASCADE,
    FOREIGN KEY (\`created_by_user_id\`) REFERENCES users(\`id\`) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE INDEX openim_group_bindings_org_idx
  ON openim_group_bindings (org_id, instance_id)`,
  `CREATE TABLE IF NOT EXISTS ragflow_bindings (
    id VARCHAR(128) PRIMARY KEY,
    org_id VARCHAR(128) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    instance_id VARCHAR(128) NOT NULL,
    ragflow_username VARCHAR(255) NOT NULL,
    ragflow_user_id VARCHAR(128),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    UNIQUE (instance_id, user_id),
    UNIQUE (instance_id, ragflow_username),
    FOREIGN KEY (\`org_id\`) REFERENCES organizations(\`id\`) ON DELETE CASCADE,
    FOREIGN KEY (\`user_id\`) REFERENCES users(\`id\`) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE TABLE IF NOT EXISTS ragflow_audit_events (
    id VARCHAR(128) PRIMARY KEY,
    org_id VARCHAR(128) NOT NULL,
    actor_user_id VARCHAR(128) NOT NULL,
    target_user_id VARCHAR(128) NOT NULL,
    action VARCHAR(191) NOT NULL,
    created_at BIGINT NOT NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE INDEX ragflow_bindings_org_idx
  ON ragflow_bindings (org_id, instance_id)`,
  `CREATE INDEX ragflow_audit_org_idx
  ON ragflow_audit_events (org_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS cloud_settings (
    \`key\` VARCHAR(191) PRIMARY KEY,
    value LONGTEXT NOT NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE TABLE IF NOT EXISTS cloud_files (
    id VARCHAR(128) PRIMARY KEY,
    orgId VARCHAR(128) NOT NULL,
    ownerUserId VARCHAR(128) NOT NULL,
    parentId VARCHAR(128) NOT NULL,
    name VARCHAR(255) NOT NULL,
    kind VARCHAR(191) NOT NULL,
    size BIGINT NOT NULL,
    revision VARCHAR(191) NOT NULL,
    objectKey LONGTEXT NOT NULL,
    state VARCHAR(191) NOT NULL,
    createdAt BIGINT NOT NULL,
    updatedAt BIGINT NOT NULL,
    active_marker TINYINT GENERATED ALWAYS AS (CASE WHEN state IN ('ready','pending') THEN 1 ELSE NULL END) VIRTUAL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE UNIQUE INDEX cloud_names ON cloud_files(orgId,ownerUserId,parentId,name,active_marker)`,
  `CREATE INDEX cloud_children ON cloud_files(orgId,ownerUserId,parentId,state,id)`,
  `CREATE TABLE IF NOT EXISTS cloud_uploads (
    id VARCHAR(128) PRIMARY KEY,
    orgId VARCHAR(128) NOT NULL,
    ownerUserId VARCHAR(128) NOT NULL,
    fileId VARCHAR(128) NOT NULL,
    requestKey VARCHAR(128) NOT NULL,
    signature LONGTEXT NOT NULL,
    size BIGINT NOT NULL,
    partSize BIGINT NOT NULL,
    s3Id LONGTEXT,
    state VARCHAR(191) NOT NULL,
    expiresAt BIGINT NOT NULL,
    UNIQUE(orgId,ownerUserId,requestKey)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE TABLE IF NOT EXISTS cloud_parts (
    uploadId VARCHAR(128) NOT NULL,
    number BIGINT NOT NULL,
    size BIGINT NOT NULL,
    etag VARCHAR(191) NOT NULL,
    PRIMARY KEY(uploadId,number)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE TABLE IF NOT EXISTS cloud_multipart_cleanup (
    uploadId VARCHAR(128) PRIMARY KEY,
    dueAt BIGINT NOT NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin`,
  `CREATE INDEX users_department_idx ON users (department_id)`,
  `CREATE INDEX oauth_authorization_codes_state_idx ON oauth_authorization_codes (state)`,
]
