// Generated by scripts/generate.mjs. Edit the source contracts.
export type TaskLimits = { "maxConcurrency": number; "maxCalls": number; "maxDurationMs": number; "maxTokens": number }
export type AppTaskSummary = { "id": string; "appId": string; "instanceId": string; "title": string; "route": string; "status": "running" | "completed" | "failed" | "cancelled" | "interrupted"; "revision": number; "scopeRef": string; "attempt": number; "limits": TaskLimits; "createdAt": number; "updatedAt": number; "deadlineAt": number; "sessionId": string; "workspace"?: string; "executionCount": number; "tokens": number; "expiresAt"?: number; "summary"?: string; "progress"?: number; "result"?: unknown; "error"?: string }
export type AppExecutionSummary = { "id": string; "key": string; "taskId": string; "contextKey": string; "contextRef": string; "status": "queued" | "running" | "completed" | "failed" | "cancelled" | "interrupted"; "sequence": number; "tokens": number; "toolCalls": number; "createdAt": number; "attempt": number; "resultRef"?: string; "error"?: string }
export type AppExecutionEvent = { "eventId": string; "executionId": string; "sequence": number; "timestamp": number; "type": "queued" | "running" | "progress" | "completed" | "failed" | "cancelled" | "interrupted"; "tokens"?: number; "toolCalls"?: number; "lastToolName"?: string | null; "error"?: string }
export type TaskChangedEvent = { "task": AppTaskSummary }
export type ExecutionChangedEvent = { "taskId": string; "execution": AppExecutionSummary; "event": AppExecutionEvent }
export type McpConfig = { "type": "stdio" | "http" | "sse"; "command"?: string; "args"?: Array<string>; "env"?: { [key: string]: string }; "url"?: string; "headers"?: { [key: string]: string }; "disabledTools"?: Array<string>; "oauth"?: { "clientName"?: string; "clientId"?: string; "redirectUri"?: string; "authorizationServerOrigin"?: string; "resourceMetadataUrl"?: string; "authServerMetadataUrl"?: string; "callbackPort"?: number; "omitRegistrationScope"?: boolean; "xaa"?: boolean } }
export type McpTool = { "name": string; "description": string; "disabled": boolean }
export type McpConnectionCheck = { "state": "connected" | "needs-auth" | "authorized" | "unchecked" | "failed"; "tools": Array<McpTool>; "checkedAt": number; "durationMs"?: number; "truncated"?: boolean; "error"?: string; "serverInfo"?: { "name": string; "version": string } }
export type McpServer = { "name": string; "enabled": boolean; "config": McpConfig; "updatedAt": number; "credentialsMissing": boolean; "check": McpConnectionCheck | null }
export type McpCatalog = { "servers": Array<McpServer>; "resetSessionCount"?: number; "skippedBusySessionCount"?: number }
export type PlatformFile = { "name": string; "path": string; "size": number; "mediaUrl": string }
export type CloudFile = { "id": string; "parentId": string | null; "name": string; "kind": "file" | "folder"; "size": number; "revision": string; "createdAt": number; "updatedAt": number }
export type CloudTransfer = { "id": string; "transferId": string; "direction": "upload" | "download"; "name": string; "fileId": string | null; "state": "queued" | "running" | "paused" | "cancelled" | "completed"; "totalBytes": number; "transferredBytes": number; "error": string | null; "createdAt": number; "updatedAt": number }
export type CloudShare = { "id": string; "fileId": string; "name": string; "size": number; "url": string; "accessCode": string | null; "createdAt": number; "expiresAt": number | null; "revokedAt": number | null; "state": "active" | "expired" | "revoked" | "unavailable" }
export type CloudStorageStatus = { "state": "remote_disabled" | "unauthenticated" | "unconfigured" | "disabled" | "unsupported" | "unavailable" | "target_mismatch" | "forbidden" | "ready"; "version"?: number }
export type HostCapability = { "protocol": string; "method": string; "supported": boolean; "allowed": boolean; "available": boolean; "reason": string | null; "permission": string | null; "limits": { [key: string]: number }; "surfaces": Array<"ui" | "backend"> }
export type AuthoringOperation = { "operationRef": string; "kind": string; "status": string; "projectRef": string; "createdAt": number; "updatedAt": number; "result"?: { [key: string]: unknown }; "error"?: string | null; "log"?: string; "nextOffset"?: number }
export const executionLimits: {"maxConcurrency":16;"maxCalls":256;"maxDurationMs":1800000;"maxTokens":2000000;"resultPreviewBytes":32768;"resultChunkUnits":100000;"eventHistory":2000;"retentionMs":2592000000;"changeRetentionMs":604800000;"changeHistory":10000;"activeTasks":512}
export const mcpLimits: {"servers":100;"configBytes":65536}
export const contracts: Record<string, { types: string; methods: Record<string, { permission: string | null; input: object; output: object; surfaces: string[]; errors: string[]; limits?: Record<string, number> }>; events: Record<string, { permission: string | null; input: object }> }>
export const platformLimits: {"fileBytes":104857600;"inlineBase64Length":524288;"pickedFiles":100;"imageDimension":4096}
export const authoringLimits: {"concurrentBuilds":2;"buildsPerProject":1;"queuedBuilds":32;"logBytes":10485760;"retentionMs":604800000;"responseBytes":262144}
export interface TasksHostInputMap {
  "task.create": { "idempotencyKey": string; "title": string; "route"?: string; "limits"?: { "maxConcurrency"?: number; "maxCalls"?: number; "maxDurationMs"?: number; "maxTokens"?: number } }
  "task.get": { "taskId": string }
  "task.list": { "cursor"?: string; "limit"?: number }
  "task.changes": { "afterCursor"?: string; "limit"?: number }
  "task.update": { "taskId": string; "revision": number; "summary"?: string; "progress"?: number }
  "task.finish": { "taskId": string; "revision": number; "status": "completed" | "failed"; "summary"?: string; "result"?: unknown }
  "task.cancel": { "taskId": string; "reason"?: string }
  "task.resume": { "taskId": string; "revision": number }
}
export interface TasksHostOutputMap {
  "task.create": AppTaskSummary
  "task.get": AppTaskSummary
  "task.list": { "tasks": Array<AppTaskSummary>; "nextCursor": string | null }
  "task.changes": { "changes": Array<{ "cursor": string; "task": AppTaskSummary }>; "nextCursor": string; "reset": boolean; "hasMore": boolean }
  "task.update": AppTaskSummary
  "task.finish": AppTaskSummary
  "task.cancel": AppTaskSummary
  "task.resume": AppTaskSummary
}
export interface TasksHostEventMap {
  "task.changed": TaskChangedEvent
}
export interface ExecutionHostInputMap {
  "capabilities": Record<string, never>
  "execution.start": { "scopeRef": string; "idempotencyKey": string; "contextKey": string; "prompt": string; "outputSchema": { [key: string]: unknown } | boolean; "agentType"?: string; "resources"?: { "tools": Array<string> }; "timeoutMs"?: number }
  "execution.get": { "executionId": string }
  "execution.list": { "taskId": string }
  "execution.cancel": { "executionId": string; "reason"?: string }
  "execution.events": { "executionId": string; "afterSequence"?: number; "limit"?: number }
  "execution.result.read": { "resultRef": string; "offset"?: number; "limit"?: number }
}
export interface ExecutionHostOutputMap {
  "capabilities": { "environment": "local"; "structuredOutput": boolean; "contextReuse": boolean; "maxConcurrency": number; "events": boolean }
  "execution.start": AppExecutionSummary
  "execution.get": AppExecutionSummary
  "execution.list": { "executions": Array<AppExecutionSummary> }
  "execution.cancel": AppExecutionSummary
  "execution.events": { "events": Array<AppExecutionEvent>; "earliestSequence": number }
  "execution.result.read": { "text": string; "nextOffset": number | null }
}
export interface ExecutionHostEventMap {
  "execution.changed": ExecutionChangedEvent
}
export interface McpHostInputMap {
  "servers.list": Record<string, never>
  "servers.save": { "name": string; "previousName"?: string; "enabled": boolean; "config": { "type"?: "stdio" | "http" | "sse"; "command"?: string; "args"?: Array<string>; "env"?: { [key: string]: string }; "url"?: string; "headers"?: { [key: string]: string }; "disabledTools"?: Array<string>; "oauth"?: { "clientName"?: string; "clientId"?: string; "redirectUri"?: string; "authorizationServerOrigin"?: string; "resourceMetadataUrl"?: string; "authServerMetadataUrl"?: string; "callbackPort"?: number; "omitRegistrationScope"?: boolean; "xaa"?: boolean } } }
  "servers.remove": { "name": string }
  "servers.set-enabled": { "name": string; "enabled": boolean }
  "servers.inspect": { "name": string }
  "auth.start": { "name": string }
  "auth.clear": { "name": string }
}
export interface McpHostOutputMap {
  "servers.list": McpCatalog
  "servers.save": McpCatalog
  "servers.remove": McpCatalog
  "servers.set-enabled": McpCatalog
  "servers.inspect": McpCatalog
  "auth.start": McpCatalog
  "auth.clear": McpCatalog
}
export interface McpHostEventMap {
}
export interface LocalFilesHostInputMap {
  "pick": { "kind"?: "file" | "directory"; "multiple"?: boolean }
  "open": { "path": string }
  "reveal": { "path": string }
}
export interface LocalFilesHostOutputMap {
  "pick": { "paths": Array<string> }
  "open": { "opened": true }
  "reveal": { "revealed": true }
}
export interface LocalFilesHostEventMap {
}
export interface RuntimesHostInputMap {
  "python.get": Record<string, never>
}
export interface RuntimesHostOutputMap {
  "python.get": { "available": boolean; "path": string | null; "version": string | null }
}
export interface RuntimesHostEventMap {
}
export interface PlatformHostInputMap {
  "file.pick": { "kind"?: "image" | "video" | "audio" | "file"; "multiple"?: boolean }
  "file.materialize": { "fileName": string; "dataBase64": string; "transferId"?: string; "offset"?: number; "complete"?: boolean }
  "file.thumbnail": { "path": string; "width"?: number; "height"?: number }
  "file.download": { "url": string; "fileName": string }
  "screen.capture": Record<string, never>
  "shell.open-external": { "url": string }
}
export interface PlatformHostOutputMap {
  "file.pick": { "files": Array<PlatformFile> }
  "file.materialize": PlatformFile | { "transferId": string; "complete": false; "size": number }
  "file.thumbnail": { "path": string; "mediaUrl": string }
  "file.download": { "canceled": true } | { "canceled": false; "filePath": string }
  "screen.capture": PlatformFile
  "shell.open-external": { "opened": true }
}
export interface PlatformHostEventMap {
}
export interface AuditHostInputMap {
  "source.capture": Record<string, never>
  "session.open": { "sessionId": string; "toolUseId"?: string }
  "notification.publish": { "id": string; "severity": "info" | "warning" | "error"; "title": string; "message": string; "details"?: string }
}
export interface AuditHostOutputMap {
  "source.capture": { "schemaVersion": 1; "capturedAt": number; "sessionCount": number }
  "session.open": { "opened": true }
  "notification.publish": { "delivered": true }
}
export interface AuditHostEventMap {
}
export interface TraceHostInputMap {
  "status": Record<string, never>
}
export interface TraceHostOutputMap {
  "status": { "enabled": boolean; "queuedBytes": number; "droppedRecords": number; "error": string | null }
}
export interface TraceHostEventMap {
}
export interface CloudStorageHostInputMap {
  "status.get": Record<string, never>
  "quota.get": Record<string, never>
  "files.list": { "parentId"?: string | null; "cursor"?: string; "limit"?: number }
  "files.get": { "fileId": string }
  "folders.create": { "name": string; "parentId"?: string | null }
  "files.update": { "fileId": string; "name"?: string; "parentId"?: string | null }
  "files.delete": { "fileId": string }
  "local-files.pick": Record<string, never>
  "uploads.start": { "handle": string; "name"?: string; "parentId"?: string | null }
  "downloads.start": { "fileId": string }
  "transfers.list": { "cursor"?: string; "limit"?: number }
  "transfers.get": { "transferId": string }
  "transfers.pause": { "transferId": string }
  "transfers.resume": { "transferId": string }
  "transfers.cancel": { "transferId": string }
  "shares.create": { "fileId": string; "requestKey": string; "expiresAt": number | null; "accessCode"?: string | null }
  "shares.list": { "fileId"?: string; "cursor"?: string; "limit"?: number }
  "shares.revoke": { "shareId": string }
}
export interface CloudStorageHostOutputMap {
  "status.get": CloudStorageStatus
  "quota.get": { "usedBytes": number; "reservedBytes": number; "limitBytes": number }
  "files.list": { "files": Array<CloudFile>; "nextCursor": string | null }
  "files.get": CloudFile
  "folders.create": CloudFile
  "files.update": CloudFile
  "files.delete": { "ok": true }
  "local-files.pick": { "files": Array<{ "handle": string; "name": string; "size": number }> }
  "uploads.start": { "transferId": string }
  "downloads.start": { "transferId": string }
  "transfers.list": { "transfers": Array<CloudTransfer>; "nextCursor": string | null }
  "transfers.get": CloudTransfer
  "transfers.pause": CloudTransfer
  "transfers.resume": CloudTransfer
  "transfers.cancel": CloudTransfer
  "shares.create": CloudShare
  "shares.list": { "shares": Array<CloudShare>; "nextCursor": string | null }
  "shares.revoke": CloudShare
}
export interface CloudStorageHostEventMap {
  "transfers.progress": CloudTransfer
  "transfers.changed": CloudTransfer
  "storage.status-changed": CloudStorageStatus
}
export interface HostHostInputMap {
  "capabilities.get": { "protocols"?: Array<string> }
  "info.get": Record<string, never>
  "contracts.list": { "kind"?: string; "offset"?: number; "limit"?: number }
  "contracts.get": { "kind": string; "member": string; "contractHash": string }
  "sdk.export": { "projectRef": string; "sdkHash": string }
}
export interface HostHostOutputMap {
  "capabilities.get": { "capabilities": Array<HostCapability> }
  "info.get": { "hostApiVersion": string; "sdkVersion": string; "manifestSchemaVersion": number; "contractHash": string; "sdkHash": string }
  "contracts.list": { "contractHash": string; "items": Array<{ "kind": string; "member": string }>; "nextOffset": number | null }
  "contracts.get": { "kind": string; "member": string; "contractHash": string; "document": { [key: string]: unknown } }
  "sdk.export": { "projectRef": string; "path": string; "sdkHash": string; "contractHash": string }
}
export interface HostHostEventMap {
}
export interface AppsHostInputMap {
  "authoring.get": Record<string, never>
  "authoring.prepare": { "intent": "create" | "edit"; "targetRef"?: string; "ref"?: { [key: string]: unknown }; "prompt"?: string }
  "catalog.list": { "kind"?: "apps" | "projects" }
  "target.inspect": { "projectRef"?: string; "targetRef"?: string; "appId"?: string }
  "source.inspect": { "projectRef"?: string; "targetRef"?: string; "appId"?: string }
  "project.prepare": { "intent": "create" | "edit"; "projectId": string; "projectRef"?: string; "draftRef"?: string; "targetRef"?: string; "appId"?: string; "sourcePath"?: string; "replaceOriginal"?: boolean }
  "build.start": { "projectRef": string; "submissionKey": string; "sourceHash": string; "contractHash": string; "sdkHash": string; "installDependencies"?: boolean }
  "build.get": { "operationRef": string; "offset"?: number; "limit"?: number }
  "build.cancel": { "operationRef": string }
  "artifact.validate": { "artifactRef": string }
  "artifact.preview": { "artifactRef": string; "submissionKey": string; "grants"?: Array<string>; "config"?: { [key: string]: unknown } }
  "artifact.test": { "previewRef": string; "action": string; "input"?: { [key: string]: unknown }; "submissionKey": string }
  "artifact.get": { "operationRef": string; "offset"?: number; "limit"?: number }
  "artifact.close": { "operationRef": string }
  "release.prepare": { "artifactRef": string; "submissionKey": string; "expectedBaseVersion": string | null; "expectedInstallationRevision": number; "dataCompatibility": "unchanged" | "migration-tested" | "unknown"; "verification"?: string }
  "release.commit": { "releaseRef": string; "submissionKey": string }
  "release.get": { "operationRef": string; "offset"?: number; "limit"?: number }
  "release.cancel": { "operationRef": string }
}
export interface AppsHostOutputMap {
  "authoring.get": { "available": boolean; "reason": string | null; "provider": { [key: string]: unknown } | null }
  "authoring.prepare": { [key: string]: unknown }
  "catalog.list": { "items": Array<{ [key: string]: unknown }> }
  "target.inspect": { [key: string]: unknown }
  "source.inspect": { [key: string]: unknown }
  "project.prepare": { [key: string]: unknown }
  "build.start": AuthoringOperation
  "build.get": AuthoringOperation
  "build.cancel": AuthoringOperation
  "artifact.validate": { [key: string]: unknown }
  "artifact.preview": AuthoringOperation
  "artifact.test": AuthoringOperation
  "artifact.get": AuthoringOperation
  "artifact.close": AuthoringOperation
  "release.prepare": AuthoringOperation
  "release.commit": AuthoringOperation
  "release.get": AuthoringOperation
  "release.cancel": AuthoringOperation
}
export interface AppsHostEventMap {
  "authoring.changed": { "revision": number }
  "operation.changed": AuthoringOperation
}
export interface HostInputMap {
  "moss.tasks/v1": TasksHostInputMap
  "moss.agent-execution/v1": ExecutionHostInputMap
  "moss.mcp/v1": McpHostInputMap
  "moss.local-files/v1": LocalFilesHostInputMap
  "moss.runtimes/v1": RuntimesHostInputMap
  "moss.platform/v1": PlatformHostInputMap
  "moss.audit/v1": AuditHostInputMap
  "moss.trace/v1": TraceHostInputMap
  "moss.cloud-storage/v1": CloudStorageHostInputMap
  "moss.host/v1": HostHostInputMap
  "moss.apps/v1": AppsHostInputMap
}
export interface HostOutputMap {
  "moss.tasks/v1": TasksHostOutputMap
  "moss.agent-execution/v1": ExecutionHostOutputMap
  "moss.mcp/v1": McpHostOutputMap
  "moss.local-files/v1": LocalFilesHostOutputMap
  "moss.runtimes/v1": RuntimesHostOutputMap
  "moss.platform/v1": PlatformHostOutputMap
  "moss.audit/v1": AuditHostOutputMap
  "moss.trace/v1": TraceHostOutputMap
  "moss.cloud-storage/v1": CloudStorageHostOutputMap
  "moss.host/v1": HostHostOutputMap
  "moss.apps/v1": AppsHostOutputMap
}
export interface HostEventMap {
  "moss.tasks/v1": TasksHostEventMap
  "moss.agent-execution/v1": ExecutionHostEventMap
  "moss.mcp/v1": McpHostEventMap
  "moss.local-files/v1": LocalFilesHostEventMap
  "moss.runtimes/v1": RuntimesHostEventMap
  "moss.platform/v1": PlatformHostEventMap
  "moss.audit/v1": AuditHostEventMap
  "moss.trace/v1": TraceHostEventMap
  "moss.cloud-storage/v1": CloudStorageHostEventMap
  "moss.host/v1": HostHostEventMap
  "moss.apps/v1": AppsHostEventMap
}
