// Generated by scripts/generate.mjs. Edit the source contracts.
export type TaskLimits = { "maxConcurrency": number; "maxCalls": number; "maxDurationMs": number; "maxTokens": number }
export type AppTaskSummary = { "id": string; "appId": string; "instanceId": string; "title": string; "route": string; "status": "running" | "completed" | "failed" | "cancelled" | "interrupted"; "revision": number; "scopeRef": string; "attempt": number; "limits": TaskLimits; "createdAt": number; "updatedAt": number; "deadlineAt": number; "sessionId": string; "workspace"?: string; "executionCount": number; "tokens": number; "summary"?: string; "progress"?: number; "result"?: unknown; "error"?: string }
export type AppExecutionSummary = { "id": string; "key": string; "taskId": string; "contextKey": string; "contextRef": string; "status": "queued" | "running" | "completed" | "failed" | "cancelled" | "interrupted"; "sequence": number; "tokens": number; "toolCalls": number; "createdAt": number; "attempt": number; "resultRef"?: string; "error"?: string }
export type AppExecutionEvent = { "eventId": string; "executionId": string; "sequence": number; "timestamp": number; "type": "queued" | "running" | "progress" | "completed" | "failed" | "cancelled" | "interrupted"; "tokens"?: number; "toolCalls"?: number; "lastToolName"?: string | null; "error"?: string }
export type TaskChangedEvent = { "task": AppTaskSummary }
export type ExecutionChangedEvent = { "taskId": string; "execution": AppExecutionSummary; "event": AppExecutionEvent }
export type McpConfig = { "type": "stdio" | "http" | "sse"; "command"?: string; "args"?: Array<string>; "env"?: { [key: string]: string }; "url"?: string; "headers"?: { [key: string]: string }; "disabledTools"?: Array<string>; "oauth"?: { "clientName"?: string; "clientId"?: string; "redirectUri"?: string; "authorizationServerOrigin"?: string; "resourceMetadataUrl"?: string; "authServerMetadataUrl"?: string; "callbackPort"?: number; "omitRegistrationScope"?: boolean; "xaa"?: boolean } }
export type McpTool = { "name": string; "description": string; "disabled": boolean }
export type McpConnectionCheck = { "state": "connected" | "needs-auth" | "authorized" | "unchecked" | "failed"; "tools": Array<McpTool>; "checkedAt": number; "durationMs"?: number; "truncated"?: boolean; "error"?: string; "serverInfo"?: { "name": string; "version": string } }
export type McpServer = { "name": string; "enabled": boolean; "config": McpConfig; "updatedAt": number; "credentialsMissing": boolean; "check": McpConnectionCheck | null }
export type McpCatalog = { "servers": Array<McpServer>; "resetSessionCount"?: number; "skippedBusySessionCount"?: number }
export const executionLimits: {"maxConcurrency":16;"maxCalls":256;"maxDurationMs":1800000;"maxTokens":2000000;"resultPreviewBytes":32768;"resultChunkUnits":100000;"eventHistory":2000}
export const mcpLimits: {"servers":100;"configBytes":65536}
export const contracts: Record<string, { types: string; methods: Record<string, { permission: string; input: object; output: object; surfaces: string[]; errors: string[]; limits?: Record<string, number> }>; events: Record<string, { permission: string; input: object }> }>
export interface TasksHostInputMap {
  "task.create": { "idempotencyKey": string; "title": string; "route"?: string; "limits"?: { "maxConcurrency"?: number; "maxCalls"?: number; "maxDurationMs"?: number; "maxTokens"?: number } }
  "task.get": { "taskId": string }
  "task.list": { "offset"?: number; "limit"?: number }
  "task.update": { "taskId": string; "revision": number; "summary"?: string; "progress"?: number }
  "task.finish": { "taskId": string; "revision": number; "status": "completed" | "failed"; "summary"?: string; "result"?: unknown }
  "task.cancel": { "taskId": string; "reason"?: string }
  "task.resume": { "taskId": string; "revision": number }
}
export interface TasksHostOutputMap {
  "task.create": AppTaskSummary
  "task.get": AppTaskSummary
  "task.list": { "tasks": Array<AppTaskSummary> }
  "task.update": AppTaskSummary
  "task.finish": AppTaskSummary
  "task.cancel": AppTaskSummary
  "task.resume": AppTaskSummary
}
export interface ExecutionHostInputMap {
  "capabilities": Record<string, never>
  "execution.start": { "scopeRef": string; "idempotencyKey": string; "contextKey": string; "prompt": string; "outputSchema": { [key: string]: unknown } | boolean; "agentType"?: string; "resources"?: { "tools": Array<string> }; "timeoutMs"?: number }
  "execution.get": { "executionId": string }
  "execution.list": { "taskId": string }
  "execution.cancel": { "executionId": string; "reason"?: string }
  "execution.events": { "executionId": string; "afterSequence"?: number; "limit"?: number }
  "execution.result.read": { "resultRef": string; "offset"?: number; "limit"?: number }
}
export interface ExecutionHostOutputMap {
  "capabilities": { "environment": "local"; "structuredOutput": boolean; "contextReuse": boolean; "maxConcurrency": number; "events": boolean }
  "execution.start": AppExecutionSummary
  "execution.get": AppExecutionSummary
  "execution.list": { "executions": Array<AppExecutionSummary> }
  "execution.cancel": AppExecutionSummary
  "execution.events": { "events": Array<AppExecutionEvent>; "earliestSequence": number }
  "execution.result.read": { "text": string; "nextOffset": number | null }
}
export interface McpHostInputMap {
  "servers.list": Record<string, never>
  "servers.save": { "name": string; "previousName"?: string; "enabled": boolean; "config": { "type"?: "stdio" | "http" | "sse"; "command"?: string; "args"?: Array<string>; "env"?: { [key: string]: string }; "url"?: string; "headers"?: { [key: string]: string }; "disabledTools"?: Array<string>; "oauth"?: { "clientName"?: string; "clientId"?: string; "redirectUri"?: string; "authorizationServerOrigin"?: string; "resourceMetadataUrl"?: string; "authServerMetadataUrl"?: string; "callbackPort"?: number; "omitRegistrationScope"?: boolean; "xaa"?: boolean } } }
  "servers.remove": { "name": string }
  "servers.set-enabled": { "name": string; "enabled": boolean }
  "servers.inspect": { "name": string }
  "auth.start": { "name": string }
  "auth.clear": { "name": string }
}
export interface McpHostOutputMap {
  "servers.list": McpCatalog
  "servers.save": McpCatalog
  "servers.remove": McpCatalog
  "servers.set-enabled": McpCatalog
  "servers.inspect": McpCatalog
  "auth.start": McpCatalog
  "auth.clear": McpCatalog
}
