export const replDarkSyntaxTheme = {
  hljs: { color: "#cdd6f0", background: "transparent" },
  "hljs-comment": { color: "#95969b", fontStyle: "italic" },
  "hljs-quote": { color: "#95969b", fontStyle: "italic" },
  "hljs-keyword": { color: "#c0b0e0" },
  "hljs-doctag": { color: "#c0b0e0" },
  "hljs-formula": { color: "#c0b0e0" },
  "hljs-section": { color: "#d8a8b0" },
  "hljs-name": { color: "#d8a8b0" },
  "hljs-selector-tag": { color: "#d8a8b0" },
  "hljs-deletion": { color: "#d8a8b0" },
  "hljs-subst": { color: "#d8a8b0" },
  "hljs-literal": { color: "#a0d8d0" },
  "hljs-string": { color: "#adddad" },
  "hljs-regexp": { color: "#adddad" },
  "hljs-addition": { color: "#adddad" },
  "hljs-attribute": { color: "#adddad" },
  "hljs-meta-string": { color: "#adddad" },
  "hljs-built_in": { color: "#b0c080" },
  "hljs-class .hljs-title": { color: "#b0c080" },
  "hljs-attr": { color: "#d8a870" },
  "hljs-variable": { color: "#d8a870" },
  "hljs-template-variable": { color: "#d8a870" },
  "hljs-type": { color: "#d8a870" },
  "hljs-selector-class": { color: "#d8a870" },
  "hljs-selector-attr": { color: "#d8a870" },
  "hljs-selector-pseudo": { color: "#d8a870" },
  "hljs-number": { color: "#d8a870" },
  "hljs-symbol": { color: "#90b8e4" },
  "hljs-bullet": { color: "#90b8e4" },
  "hljs-link": { color: "#90b8e4", textDecoration: "underline" },
  "hljs-meta": { color: "#90b8e4" },
  "hljs-selector-id": { color: "#90b8e4" },
  "hljs-title": { color: "#90b8e4" },
  "hljs-emphasis": { fontStyle: "italic" },
  "hljs-strong": { fontWeight: "bold" },
} as const;
